### ISSUE TITLE
Specifiy the functionality of the buttons

### ISSUE THREAD

**Issue by vivekdhir77** [siddarthreddygsr/Bull-game#2]
<img width="342" alt="Screenshot 2021-05-14 at 12 34 46 AM" src="https://user-images.githubusercontent.com/73019433/118174229-2ff48400-b44c-11eb-8951-ac34f5b0737f.png">

When pressed on:

> player vs player  -> Next -> Try playing with CPU

You will land at CPU vs player layout and you will be able to see 3 "Back" buttons. Please specify the functionality of each button.

**Comment by siddarthreddygsr** [comment]
issue fixed
